POST http://localhost:3001/api/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbmFzaSIsImlkIjoiNWY0MTBlMmIwNTNjYjNiNDZjZjhhYThiIiwiaWF0IjoxNTk4MTAwNTYyfQ.4NYXo2RMgdV2M7PelrhHN0s9BoqaQYc39CRbuQZzwQ8

{
    "name": "It was good",  
}
